stages:
  - stage: Build
    jobs:
      - job: 
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '6.0.201'
              includePreviewVersions: true
          - task: CmdLine@2
            displayName: 'Restore dotnet tools'
            inputs:
              script: 'dotnet tool restore'
          - task: CmdLine@2
            displayName: 'Build the project'
            inputs:
              script: 'dotnet fake run ./.build/build.fsx --target build -d'
