stages:
  - stage: Deploy_2_nugetorg 
    dependsOn: Build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs: 
      - job: 
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '6.0.x'
              includePreviewVersions: true
          - task: CmdLine@2
            inputs:
              script: 'dotnet tool restore'
          - task: CmdLine@2
            inputs:
              script: "dotnet fake run ./.build/build.fsx --target publish"
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: './artifacts/'
              artifact: 'nugets'
              publishLocation: 'pipeline'  
          - task: NuGetCommand@2
            inputs:
              command: 'push'
              packagesToPush: './artifacts/*.nupkg;!./artifacts/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'nuget-hive-net'
